In [1]:
import pandas as pd
dalhousie = pd.read_csv('dalhousie_university.csv')

In [2]:
dalhousie.shape

(20, 9)

In [3]:
dalhousie.isnull()

,Unnamed: 0,source,author,title,description,url,urlToImage,publishedAt,content
0,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,True,False,False,False,True,False,False
7,False,False,True,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,True,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [4]:
modifiedDal = dalhousie.fillna("NaN")

In [5]:
modifiedDal.isnull()

,Unnamed: 0,source,author,title,description,url,urlToImage,publishedAt,content
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [6]:
modifiedDal.head()

,Unnamed: 0,source,author,title,description,url,urlToImage,publishedAt,content
0,0,"{'id': None, 'name': 'Halifaxtoday.ca'}",The Conversation,Decision to deploy genetically modified mosqui...,Decision to deploy genetically modified mosqui...,https://www.halifaxtoday.ca/local-news/decisio...,https://www.vmcdn.ca/f/files/baytoday/images/o...,2019-10-14T15:53:00Z,"This article, written by Natalie Kofler, Unive..."
1,1,"{'id': None, 'name': 'Mississauga.com'}",NaN,Scientist faces criticism on red meat study - ...,Scientist faces criticism on red meat study Wa...,https://www.mississauga.com/community-story/96...,https://www.waterloochronicle.ca/Contents/Imag...,2019-10-06T03:06:46Z,HALIFAX A Canadian researcher who co-led a stu...
2,2,"{'id': None, 'name': 'Thetelegram.com'}",Sharon Kirkey,"No, beef isn't bad for you: Scientists conclud...","No, beef isn't bad for you: Scientists conclud...",https://www.thetelegram.com/news/canada/no-bee...,https://www.thetelegram.com/media/photologue/p...,2019-10-05T19:44:25Z,New guidelines certain to be celebrated by ent...
3,3,"{'id': None, 'name': 'Runningmagazine.ca'}",Canadian Running,Red meat: study shows the danger may be less t...,Red meat: study shows the danger may be less t...,https://runningmagazine.ca/health-nutrition/re...,https://runningmagazine.ca/wp-content/uploads/...,2019-10-02T20:05:41Z,Runners who derive a significant portion of th...
4,4,"{'id': None, 'name': 'Castanet.net'}",NaN,Study: red meat not so bad? - Canada News - Ca...,A Canadian researcher who co-led a study that ...,https://www.castanet.net/news/Canada/267557/St...,https://www.castanet.net/content/2019/10/CPT10...,2019-10-06T13:55:00Z,A Canadian researcher who co-led a study that ...

In [7]:
modifiedDal.description[9]

'New guidelines suggest there isn’t enough evidence to recommend cutting back on red meat to prevent heart disease, diabetes, and early death. But several scientists disagree with the controversial findings. Learn more about the analysis here.'

In [8]:
modifiedDal.description[8]

'Contrary to previous advice, five new systematic reviews suggest that most people can continue to eat red and processed meat as they do now. The major studies have found cutting back has little impact on health.'

In [9]:
import re

In [1]:
import re

TAG_RE = re.compile(r'<[^>]+>')

def remove_tags(modifiedDal):
    return TAG_RE.sub('', modifiedDal)

In [2]:
modifiedDal.to_csv('clean_dalhousie_universtiy.csv', index=True)

NameError: name 'modifiedDal' is not defined